export const New_Work_Items = [
    { Name: 'Bug', OrderBy: 1 },
    { Name: 'ChangeRequest', OrderBy: 2 },
    { Name: 'Epic', OrderBy: 3 },
    { Name: 'Feature', OrderBy: 4 },
    { Name: 'Issue', OrderBy: 5 },
    { Name: 'Observation', OrderBy: 6 },
    { Name: 'Risk', OrderBy: 7 },
    { Name: 'Subtask', OrderBy: 8 },
    { Name: 'Task', OrderBy: 9 },
    { Name: 'Test', OrderBy: 10 },
    { Name: 'TestCase', OrderBy: 11 },
    { Name: 'UserStory', OrderBy: 12 },
]
export const Work_Item_States = [
    { Name: 'New', OrderBy: 1 },
    { Name: 'In Progress', OrderBy: 2 },
    { Name: 'Resolved', OrderBy: 3 },
    { Name: 'Closed', OrderBy: 4 },
    { Name: 'Active', OrderBy: 5 },
    { Name: 'Removed', OrderBy: 6 },
    { Name: 'Ready For Development', OrderBy: 7 },
    { Name: 'Development', OrderBy: 8 },
    { Name: 'In Development', OrderBy: 9 },
    { Name: 'Development Complete', OrderBy: 10 },
    { Name: 'Deploy In  Development Server', OrderBy: 11 },
    { Name: 'Design', OrderBy: 12 },
    { Name: 'In QA', OrderBy: 13 },
    { Name: 'QA Complete', OrderBy: 14 },
    { Name: 'Deploy In QA Server', OrderBy: 15 },
    { Name: 'Ready For UAT', OrderBy: 16 },
    { Name: 'UAT', OrderBy: 17 },
    { Name: 'UAT Complete', OrderBy: 18 },
    { Name: 'Deploy In UAT Server', OrderBy: 19 },
    { Name: 'Ready For Production', OrderBy: 20 },
    { Name: 'Production', OrderBy: 21 },
    { Name: 'Production Complete', OrderBy: 22 },
    { Name: 'Deploy In Production Server', OrderBy: 23 },
]

export const Work_Item_Priority = [
    { Id: 1, Name: 'Low', OrderBy: 1 },
    { Id: 2, Name: 'Medium', OrderBy: 2 },
    { Id: 3, Name: 'High', OrderBy: 3 },
]
export const Work_Item_Status = [
    { Id: 1, Name: 'Planned', OrderBy: 1 },
    { Id: 2, Name: 'In progress', OrderBy: 2 },
    { Id: 3, Name: 'Completed', OrderBy: 3 },
]
export const APP_User_Data = [
    { Id: 1, Name: 'John Doe', Email: 'john.doe@example.com', Designation: 'Software Engineer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 2, Name: 'Aarav Sharma', Email: 'aarav.sharma@example.com', Designation: 'Senior Developer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 3, Name: 'Emma Johnson', Email: 'emma.johnson@example.com', Designation: 'QA Analyst', Department: 'Quality Assurance', Role: 'Tester', Status: 'Active' },
    { Id: 4, Name: 'Liam Carter', Email: 'liam.carter@example.com', Designation: 'Product Manager', Department: 'Product', Role: 'Manager', Status: 'Active' },
    { Id: 5, Name: 'Sofia Martinez', Email: 'sofia.martinez@example.com', Designation: 'UI/UX Designer', Department: 'Design', Role: 'Designer', Status: 'Active' },
    { Id: 6, Name: 'Noah Brown', Email: 'noah.brown@example.com', Designation: 'DevOps Engineer', Department: 'Infrastructure', Role: 'Engineer', Status: 'Active' },
    { Id: 7, Name: 'Olivia Davis', Email: 'olivia.davis@example.com', Designation: 'Business Analyst', Department: 'Operations', Role: 'Analyst', Status: 'Inactive' },
    { Id: 8, Name: 'Mason Wilson', Email: 'mason.wilson@example.com', Designation: 'Frontend Developer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 9, Name: 'Ava Taylor', Email: 'ava.taylor@example.com', Designation: 'HR Manager', Department: 'Human Resources', Role: 'Manager', Status: 'Active' },
    { Id: 10, Name: 'Lucas Moore', Email: 'lucas.moore@example.com', Designation: 'System Administrator', Department: 'IT', Role: 'Administrator', Status: 'Active' },
    { Id: 11, Name: 'Isabella Jackson', Email: 'isabella.jackson@example.com', Designation: 'Technical Lead', Department: 'Development', Role: 'Lead', Status: 'Active' },
    { Id: 12, Name: 'Ethan White', Email: 'ethan.white@example.com', Designation: 'Automation Engineer', Department: 'Quality Assurance', Role: 'Engineer', Status: 'Active' },
    { Id: 13, Name: 'Mia Harris', Email: 'mia.harris@example.com', Designation: 'Sales Executive', Department: 'Sales', Role: 'Executive', Status: 'Active' },
    { Id: 14, Name: 'James Martin', Email: 'james.martin@example.com', Designation: 'Support Engineer', Department: 'Support', Role: 'Engineer', Status: 'Inactive' },
    { Id: 15, Name: 'Charlotte Thompson', Email: 'charlotte.thompson@example.com', Designation: 'Project Coordinator', Department: 'Project Management', Role: 'Coordinator', Status: 'Active' },
    { Id: 16, Name: 'Benjamin Garcia', Email: 'benjamin.garcia@example.com', Designation: 'Backend Developer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 17, Name: 'Harper Robinson', Email: 'harper.robinson@example.com', Designation: 'Marketing Manager', Department: 'Marketing', Role: 'Manager', Status: 'Active' },
    { Id: 18, Name: 'Henry Clark', Email: 'henry.clark@example.com', Designation: 'Database Administrator', Department: 'Data', Role: 'Administrator', Status: 'Active' },
    { Id: 19, Name: 'Amelia Rodriguez', Email: 'amelia.rodriguez@example.com', Designation: 'Security Analyst', Department: 'Security', Role: 'Analyst', Status: 'Active' },
    { Id: 20, Name: 'Alexander Lewis', Email: 'alexander.lewis@example.com', Designation: 'Mobile Developer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 21, Name: 'Evelyn Walker', Email: 'evelyn.walker@example.com', Designation: 'Recruitment Specialist', Department: 'Human Resources', Role: 'Specialist', Status: 'Inactive' },
    { Id: 22, Name: 'Daniel Hall', Email: 'daniel.hall@example.com', Designation: 'Data Engineer', Department: 'Data', Role: 'Engineer', Status: 'Active' },
    { Id: 23, Name: 'Abigail Allen', Email: 'abigail.allen@example.com', Designation: 'Quality Engineer', Department: 'Quality Assurance', Role: 'Engineer', Status: 'Active' },
    { Id: 24, Name: 'Michael Young', Email: 'michael.young@example.com', Designation: 'Network Engineer', Department: 'Infrastructure', Role: 'Engineer', Status: 'Active' },
    { Id: 25, Name: 'Ella Hernandez', Email: 'ella.hernandez@example.com', Designation: 'Customer Success Manager', Department: 'Customer Success', Role: 'Manager', Status: 'Active' },
    { Id: 26, Name: 'Jacob King', Email: 'jacob.king@example.com', Designation: 'Cloud Engineer', Department: 'Infrastructure', Role: 'Engineer', Status: 'Active' },
    { Id: 27, Name: 'Scarlett Wright', Email: 'scarlett.wright@example.com', Designation: 'Content Strategist', Department: 'Marketing', Role: 'Strategist', Status: 'Active' },
    { Id: 28, Name: 'Logan Lopez', Email: 'logan.lopez@example.com', Designation: 'Java Developer', Department: 'Development', Role: 'Developer', Status: 'Inactive' },
    { Id: 29, Name: 'Grace Hill', Email: 'grace.hill@example.com', Designation: 'Financial Analyst', Department: 'Finance', Role: 'Analyst', Status: 'Active' },
    { Id: 30, Name: 'Sebastian Scott', Email: 'sebastian.scott@example.com', Designation: 'Operations Manager', Department: 'Operations', Role: 'Manager', Status: 'Active' },
    { Id: 31, Name: 'Chloe Green', Email: 'chloe.green@example.com', Designation: 'Frontend Engineer', Department: 'Development', Role: 'Engineer', Status: 'Active' },
    { Id: 32, Name: 'Jack Adams', Email: 'jack.adams@example.com', Designation: 'Scrum Master', Department: 'Project Management', Role: 'Manager', Status: 'Active' },
    { Id: 33, Name: 'Victoria Baker', Email: 'victoria.baker@example.com', Designation: 'UX Researcher', Department: 'Design', Role: 'Researcher', Status: 'Active' },
    { Id: 34, Name: 'Owen Gonzalez', Email: 'owen.gonzalez@example.com', Designation: 'Test Engineer', Department: 'Quality Assurance', Role: 'Engineer', Status: 'Active' },
    { Id: 35, Name: 'Luna Nelson', Email: 'luna.nelson@example.com', Designation: 'Account Manager', Department: 'Sales', Role: 'Manager', Status: 'Active' },
    { Id: 36, Name: 'Wyatt Carter', Email: 'wyatt.carter@example.com', Designation: 'Cyber Security Engineer', Department: 'Security', Role: 'Engineer', Status: 'Active' },
    { Id: 37, Name: 'Nora Mitchell', Email: 'nora.mitchell@example.com', Designation: 'Release Manager', Department: 'Operations', Role: 'Manager', Status: 'Inactive' },
    { Id: 38, Name: 'Gabriel Perez', Email: 'gabriel.perez@example.com', Designation: 'Platform Engineer', Department: 'Infrastructure', Role: 'Engineer', Status: 'Active' },
    { Id: 39, Name: 'Hazel Roberts', Email: 'hazel.roberts@example.com', Designation: 'Digital Marketing Specialist', Department: 'Marketing', Role: 'Specialist', Status: 'Active' },
    { Id: 40, Name: 'Julian Turner', Email: 'julian.turner@example.com', Designation: 'Software Engineer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 41, Name: 'Aria Phillips', Email: 'aria.phillips@example.com', Designation: 'Support Specialist', Department: 'Support', Role: 'Specialist', Status: 'Active' },
    { Id: 42, Name: 'Nathan Campbell', Email: 'nathan.campbell@example.com', Designation: 'Application Developer', Department: 'Development', Role: 'Developer', Status: 'Active' },
    { Id: 43, Name: 'Layla Parker', Email: 'layla.parker@example.com', Designation: 'Business Systems Analyst', Department: 'Operations', Role: 'Analyst', Status: 'Active' },
    { Id: 44, Name: 'Isaac Evans', Email: 'isaac.evans@example.com', Designation: 'Machine Learning Engineer', Department: 'Data', Role: 'Engineer', Status: 'Active' },
    { Id: 45, Name: 'Zoe Edwards', Email: 'zoe.edwards@example.com', Designation: 'Product Analyst', Department: 'Product', Role: 'Analyst', Status: 'Inactive' },
    { Id: 46, Name: 'Levi Collins', Email: 'levi.collins@example.com', Designation: 'Systems Engineer', Department: 'IT', Role: 'Engineer', Status: 'Active' },
    { Id: 47, Name: 'Penelope Stewart', Email: 'penelope.stewart@example.com', Designation: 'Compliance Officer', Department: 'Administration', Role: 'Officer', Status: 'Active' },
    { Id: 48, Name: 'David Sanchez', Email: 'david.sanchez@example.com', Designation: 'Senior QA Engineer', Department: 'Quality Assurance', Role: 'Engineer', Status: 'Active' },
    { Id: 49, Name: 'Ruby Morris', Email: 'ruby.morris@example.com', Designation: 'Technical Writer', Department: 'Documentation', Role: 'Writer', Status: 'Active' },
    { Id: 50, Name: 'Samuel Rogers', Email: 'samuel.rogers@example.com', Designation: 'Principal Engineer', Department: 'Development', Role: 'Engineer', Status: 'Active' },
];

